<a href="https://colab.research.google.com/github/hungry4therock/Colab/blob/main/2_Numpy_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
내용:파이썬 numpy 패키지 실습
"""
import numpy  as np



In [ ]:
# numpy 자료구조 - 백터
v1 = np.array([1,2,3,4,5])
print(v1)

v2 = np.arange(5)
print(v2)

v3 = np.arange(10)
print('v3:',v3)


[1 2 3 4 5]
[0 1 2 3 4]
v3: [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 0~1 사이 임의의 실수
rand1 = np.random.rand(100)
print(rand1)

# 표준 정규분포를 따르는 실수 100개
rand2 = np.random.randn(100)
print(rand2)

# 0~9 사이의 임의의 정수
rand3 = np.random.randn(100)
print(rand3)

[0.04822829 0.05389402 0.54762897 0.21474723 0.48935464 0.765268
 0.18141816 0.25035049 0.2433612  0.63127623 0.09765149 0.0538403
 0.16525207 0.80692769 0.1559048  0.76124214 0.05646561 0.68756032
 0.61338667 0.62261812 0.91311226 0.51906184 0.55192662 0.46578767
 0.7897533  0.65083533 0.18127249 0.49175772 0.30635613 0.52323788
 0.26674705 0.17148322 0.73659739 0.42617416 0.69428733 0.39846602
 0.59798131 0.0356161  0.10742672 0.27028144 0.50726979 0.11720154
 0.82331317 0.34957573 0.39222723 0.41004548 0.80419972 0.66411183
 0.57662243 0.22201339 0.34354071 0.76628004 0.60102196 0.20012995
 0.15744489 0.50323753 0.28825947 0.5172277  0.41307353 0.20358487
 0.35995184 0.20530493 0.2067806  0.14825952 0.72820025 0.79818418
 0.42804066 0.85096614 0.35222596 0.25522611 0.60979633 0.96956333
 0.15649105 0.01053985 0.21896261 0.08304551 0.20690304 0.71093675
 0.08566909 0.79520085 0.21656369 0.53675621 0.38766392 0.28693713
 0.86726693 0.74314979 0.47634379 0.35168711 0.77432905 0.1138353

In [ ]:
# numpy 자료구조 - 행렬
m1 = np.array([[1,2],[3,4]])
print(m1)

m2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m2)

m3 = np.ones([2,4])
print(m3)

m4 = np.zeros([3,2])
print(m4)


[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# 전치행렬
m1.T 

print(m2.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
# 단위행렬
e1 = np.identity(2)
print(e1)

e2 = np.identity(3)
print(e2)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 역행렬
im1 = np.linalg.inv(m1)
print(im1)

result = m1.dot(im1)
print(result.round())

print(m1*im1)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]
[[-2.   2. ]
 [ 4.5 -2. ]]


In [ ]:
#행렬 인덱싱
matrix = np.array([
                   [1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]
                   ])
print(matrix)

print(matrix[0, 0])
print(matrix[0, :])
print(matrix[:, 0])

print(matrix[0:2, 0:2])
print(matrix[:, 0:2])
print(matrix[:, 2:4])
print(matrix[1:3, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[1 2 3 4]
[1 5 9]
[[1 2]
 [5 6]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]
